### ISSUE TITLE
IR camera

### ISSUE THREAD

**Issue by manatactical** [brian7704/OpenTAK_ICU#1]
Hi there (It's not an issue, more like a technical question)

Great plugin so far. I use it on my dirt cheat Ulefone X13 off-grid. I would like to know if somehow the plugin can detect more camera inputs in order to use them? (got the regular one and an infra red camera).

Thanks!
Keep up the good work!

**Comment by brian7704** [comment]
That's a neat device, I've never heard of it. Are you asking if OpenTAK ICU can enable its IR LEDs? Or are you plugging in a USB camera? USB cameras aren't supported yet but it's on the list of features I want to add. But if you mean your phone's IR LEDs, I'm not sure. I've never seen a device that has them but my guess is that it has some unique API I'd need to use in order to enable them.

**Comment by manatactical** [comment]
The IR Camera (and the IR LEDs) are built-in. So no USB devices. But they are not recognized in OpenTAK ICU.
Here is the phone if you are curious: https://www.ulefone.com/armor-x13.html

I'm no android developer sadly, so I don't know how built-in cameras are retrieved by the API.

**Comment by brian7704** [comment]
I see. Usually the rear camera changes automatically based on zoom level. However it must be different on your device since the second camera is for IR. I'll see what I can do.

**Comment by manatactical** [comment]
If you need me to beta test things like that (like pre-released APK), hit me up.

**Comment by brian7704** [comment]
Can you install [this APK](https://github.com/vibhorSrv/CameraIDs/releases/tag/1.2) and post the output here?

**Comment by manatactical** [comment]
And voila

`2024 M03 26, Tue 06:11:06 GMT+01:00

============================

Device : Ulefone Armor X13 (Armor_X13)
Manufacturer : Ulefone
Android : 13
Fingerprint : Ulefone/Armor_X13_EEA/Armor_X13:13/TP1A.220624.014/1692260679:user/release-keys

============================

Camera IDs Visible to Apps = [0, 1]

============================

All Camera IDs = [0, 1, 2]

============================

CameraID = [0]  ★
Facing = BACK
Zoom = 1x
Type = MAIN
FocalLength = 4.23mm
35mm eqv FocalLength = 29.23mm
Aperture = 1.8
SensorSize = 5.21x3.91
PixelArray = 8160x6144
PixelSize = 0.64µm
AngleOfView(Diagonal) = 52°
AEModes = [0, 1, 2, 3]
FlashSupported = true
RAW_SENSOR sizes = [4080x3072]
SupportedHardwareLevel = FULL

============================

CameraID = [1]  ★
Facing = FRONT
Zoom = 1x
Type = MAIN
FocalLength = 2.85mm
35mm eqv FocalLength = 28.11mm
Aperture = 2.0
SensorSize = 3.65x2.74
PixelArray = 3264x2448
PixelSize = 1.12µm
AngleOfView(Diagonal) = 84°
AEModes = [0, 1, 5]
FlashSupported = false
RAW_SENSOR sizes = null
SupportedHardwareLevel = FULL

============================

CameraID = [2]  ★
Facing = BACK
Zoom = 0.65x
Type = DEPTH
FocalLength = 3.52mm
35mm eqv FocalLength = 19.08mm
Aperture = 1.8
SensorSize = 6.64x4.97
PixelArray = 5664x4320
PixelSize = 1.17µm
AngleOfView(Diagonal) = 108°
AEModes = [0, 1, 2, 3]
FlashSupported = false
RAW_SENSOR sizes = null
SupportedHardwareLevel = 3`

**Comment by manatactical** [comment]
Hello there,

Any update regarding my last message?

Thanks for your time ;)

**Comment by brian7704** [comment]
Unfortunately not. I'd probably need a device with an IR camera to get it working but I don't have one.

**Comment by brian7704** [comment]
I finally got a device with an IR camera that I was able to get working. Can you try [this APK](http://docs.opentakserver.io/OpenTAK_ICU_IR_Camera_Debug.apk) and see if it works on your device as well?

**Comment by brian7704** [comment]
I forgot to mention, toggling the IR LED's requires root unfortunately. Even if your device  isn't rooted I'd be interested to know if this APK can access the IR camera.

**Comment by brian7704** [comment]
Someone in the Discord server was able to test the APK with the Ulefone Armor X13 and Armor 22 which both worked. I'll release an updated APK soon.
