### ISSUE TITLE
Missing keystore.properties in git zip OpenTAK_ICU-master.zip

### ISSUE THREAD

**Issue by davidcarlsonSEE** [brian7704/OpenTAK_ICU#10]
Hi, get the following error when trying to open the unzipped master project in Android Studio Koala | 2024.1.1 Patch 2.
 C:\sourceAndroid\camearproject\OpenTAK_ICU-master\keystore.properties (The system cannot find the file specified)

There are other errors but I have a feeling this may be causing the other cascading errors.

Any Ideas?

**Comment by brian7704** [comment]
You'll need to make a keystore in Android Studio to sign your builds. Then you can change [this line](https://github.com/brian7704/OpenTAK_ICU/blob/master/app%2Fbuild.gradle.kts#L7) to point to your keystore.properties file. Here are the docs on [making a keystore](https://developer.android.com/studio/publish/app-signing)

**Comment by davidcarlsonSEE** [comment]
Thanks,  at first I thought I had to use a key you provided.  I created a keystore with the keytool outside of android studio then a properties file with the correct variable names.  Then linked it all up back in android studio.

**Comment by brian7704** [comment]
Glad you got it working. Just so you know, the keystore is private and shouldn't be shared. If you build a version of OpenTAK ICU with the same `io.opentakserver.opentakicu` package name and sign it with your key, it would conflict with my builds. That just means that you couldn't have my build and your build on the same device at the same time.

**Comment by davidcarlsonSEE** [comment]
Got it.  If I built a version for use with our ATAK plug-in I would certainly change the package name to com.safeenv.opentak or something like that.
