### ISSUE TITLE
Doesn't seem to send auth for rtmp/rtmps

### ISSUE THREAD

**Issue by sgofferj** [brian7704/OpenTAK_ICU#5]
I'm trying to stream via rtmps to an address requiring auth. Username and password are set in the settings but mediamtx reports authentication failure:

```
mediamtx-1  | 2024/05/17 09:35:47 INF [RTMPS] [conn xxx.xxx.xxx.xxx:51440] opened
mediamtx-1  | 2024/05/17 09:35:49 INF [RTMPS] [conn xxx.xxx.xxx.xxx:51440] closed: authentication failed: server replied with code 401: {"ip":"xxx.xxx.xxx.xxx","user":"","password":"","action":"publish","path":"live/xxxxxx","protocol":"rtmp","id":"89ea0f3b-8708-45a2-a7c6-f109c17776e1","query":""}
```

**Comment by sgofferj** [comment]
Same for rtmp.

**Comment by brian7704** [comment]
I think this is an issue with the RootEncoder library that handles streaming in OpenTAK ICU. I've opened an issue on their repo pedroSG94/RootEncoder#1484

**Comment by brian7704** [comment]
This issue was actually due to the non-standard way that MediaMTX handles authentication. I added support for it in [1.4.4](https://github.com/brian7704/OpenTAK_ICU/releases/tag/1.4.4).
